exclude: ^(vendor|.vscode)/
repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.21.2
  hooks:
  - id: commitizen
    stages: [commit-msg]
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
  - id: go-fmt
  - id: go-mod-vendor
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
    exclude_types: [markdown]
  - id: trailing-whitespace
    exclude_types: [markdown]
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: check-added-large-files
- repo: https://github.com/golangci/golangci-lint
  rev: v1.55.2
  hooks:
  - id: golangci-lint
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
