name: tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, closed]
    branches:
    - main
  push:
    branches:
    - main
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event.pull_request.action != 'closed' || github.event.pull_request.merged == true)
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run golanci Linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Run the Tests
      run: |
        go test ./... -race -coverprofile coverage.out -covermode atomic
        go tool cover -func coverage.out

    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: 6b8dd629f4688058b42919af90eb9540b6e779f0522527a6596f9080b962c451
      with:
        coverageCommand: go tool cover -func coverage.out

  release:
    name: Release
    needs: validate
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event.pull_request.merged == true)
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: v
        major_pattern: (breaking)
        minor_pattern: (feat)
        format: ${major}.${minor}.${patch}
